package com.github.juliakas.mybatis.dao;

import com.github.juliakas.mybatis.model.Company;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CompaniesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANIES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    int deleteByPrimaryKey(Long compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANIES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANIES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    Company selectByPrimaryKey(Long compId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANIES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    List<Company> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANIES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    int updateByPrimaryKey(Company record);
}