package com.github.juliakas.mybatis.dao;

import com.github.juliakas.mybatis.model.Employee;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface EmployeesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    int deleteByPrimaryKey(Long empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    Employee selectByPrimaryKey(Long empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEES
     *
     * @mbg.generated Sat Apr 11 13:09:36 EEST 2020
     */
    int updateByPrimaryKey(Employee record);

    List<Employee> selectByManager(Long managerId);
}